#!/bin/sh
# TalkOS Build Config
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --architecture amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --security false \
    --iso-application "TalkOS" \
    --iso-publisher "TalkOS Project" \
    --iso-volume "TalkOS-amd64" \
    --bootappend-live "boot=live components locales=tr_TR.UTF-8 keyboard-layouts=tr splash quiet" \
    "${@}"
